default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cohort_grouper_development

test:
  <<: *default
  database: cohort_grouper_test

production:
  <<: *default
  database: cohort_grouper_production
